### ISSUE TITLE
关于 objectchecker  中 sorted 用法 兼容问题

### ISSUE THREAD

**Issue by hackfengJam** [pastgift/route-loader-py#1]
commit code: 1fc511b0

[objectchecker.py](https://github.com/pastgift/route-loader-py/blob/1fc511b0f57d64fde66c83add9cd3f12e96e9c40/objectchecker.py) 
第 255 行，`sorted(options.items(), type_check_first_cmp)`，
此方式适合python2

官方文档关于 sorted 参数列表描述：

      |         版本         |       描述       |
      |---------------------|--------------------------------------------------|
      |     python 2        | sorted(iterable, cmp=None, key=None, reverse=False) |
      |     python 3.6      | sorted(iterable, *, key=None, reverse=False)|

官方建议：Use [functools.cmp_to_key()](https://docs.python.org/3/library/functools.html#functools.cmp_to_key) to convert an old-style cmp function to a key function.

因此处于python版本兼容考虑，
建议改成：`sorted(options.items(), key=functools.cmp_to_key(type_check_first_cmp))`

**Comment by pastgift** [comment]
已修复，感谢你的反馈 👍
